global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'bucki_exporter'
    static_configs:
    - targets: ['bucki-exporter:9889']
